server:
  port: 8002
  ssl:
    key-store: classpath:keystore/baeldung.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: baeldung
    enabled: true
trust:
  store: classpath:keystore/baeldung.p12
  store.password: 123456

app:
  domain: http://localhost:8080/storage/uploads/
  root-content-path: C:/Users/orisu/Desktop/DATN 2023/web/uploads/
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stovizkj_webtoon_hau?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Bangkok&createDatabaseIfNotExist=true
    username: stovizkj_webtoon_hau
    password: $Abcd1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoannvph17079@fpt.edu.vn
    password: <login password to smtp server>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 432444247989026
            client-secret: d73418162457ad431c83ec4665185199
          google:
            client-id: 939698702223-00eugrq3fg2pfa2fd0t6taj0a611hnhr.apps.googleusercontent.com
            client-secret: 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
logging:
  level:
    .org.springframework.web: DEBUG
    .org.hibernate: ERROR

