package webtoon.account.entities;

public enum EAuthorityConstants {
//    ROLE_ADD_EDIT_USER,
//    ROLE_DELETE_USER,
//    ROLE_ADD_EDIT_MANGA,
//    ROLE_DELETE_MANGA,
//
//    ROLE_ADD_EDIT_MANGA_GENRE,
//    ROLE_DELETE_MANGA_GENRE,
//
//    ROLE_ADD_EDIT_MANGA_AUTHOR,
//    ROLE_DELETE_MANGA_AUTHOR,
//
//    ROLE_ADD_EDIT_ORDER,
//    ROLE_DELETE_ORDER,
//
//    ROLE_ADD_EDIT_CATEGORY,
//    ROLE_DELETE_CATEGORY,
//
//    ROLE_ADD_EDIT_POST,
//    ROLE_DELETE_POST,
//
//    ROLE_ADD_EDIT_COMMENT,
//    ROLE_DELETE_COMMENT,
//
//    ROLE_ADD_EDIT_TAG,
//    ROLE_DELETE_TAG,
//
//    ROLE_VIEW_STATISTIC,

    ROLE_ADMIN,
    ROLE_USER,

    ROLE_MANGA_MANAGEMENT,
    ROLE_ORDER_MANAGEMENT,

}
